### ISSUE TITLE
error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

### ISSUE THREAD

**Issue by MSNarry** [atulapra/Emotion-detection#11]
The single face with TFLearn is working perfectly, but both the muiface and the keras are giving the same error. It seems that it is not having the frame correctly as I put:

```
ret, frame = cap.read()
    if not ret:
        print("Could not read frame")
    else :
```
and it is continuously printing "Could not read frame". Has someone solve this? I am working reading a video so I changed cap = cv2.VideoCapture(0) to cap = cv2.VideoCapture('diner.mp4'), that's the only change I made

**Comment by atulapra** [comment]
In the multiface code, there was a small typo which was causing an error. I have updated this. 
I have tested the keras code on video files of different formats and it seems to work fine, except that at the end of some videos, `ret` becomes False. I have also changed the code here to break when `ret` becomes False. However, for me `ret` does not become False in the middle or start of the video, as you have observed.  
Maybe you could send the video to atulbalaji318@gmail.com and I can test it.
