### ISSUE TITLE
Import image

### ISSUE THREAD

**Issue by hhucyl** [atulapra/Emotion-detection#13]
Hi, how can I import a random .jpg file?

**Comment by atulapra** [comment]
Currently, the code works by taking the input from the webcam for detecting emotions. To modify this to work for a .jpg file, you must read the file using opencv and provide the object as input for the haar cascade classifier [here.](https://github.com/atulapra/Emotion-detection/blob/5d4a1a6eaee68349c6ce6b9d23e62f85deaff657/Keras/kerasmodel.py#L119)

**Comment by hhucyl** [comment]
Thx
