### ISSUE TITLE
Color image is passed to model for prediction

### ISSUE THREAD

**Issue by mrtpk** [atulapra/Emotion-detection#14]
Hi,

Thanks for sharing your awesome work. It works well in single face detection.

I saw that you are passing a gray image to model for single face detection and a color image to model for multi-face detection. When I passed gray image to model for multi-face, the detecion is great.

Please check.

Thanks,
Thomas.

https://github.com/atulapra/Emotion-detection/blob/5d4a1a6eaee68349c6ce6b9d23e62f85deaff657/TFLearn/multiface.py#L37

**Comment by atulapra** [comment]
Thanks for pointing this out. I will add a line to convert it to grayscale.
