### ISSUE TITLE
99% of the times "Neutral"

### ISSUE THREAD

**Issue by Antwnina** [atulapra/Emotion-detection#16]
Dear mr Balaji,
I tried your project Emotion-detection. First I faced problem with the requirements, I solved it but then in the web camera i was smiling like crazy or opening mouth for surprised but it was always “Neutral”. How can i solve this?
Thanks in advance.
Regards, 
P. Antonina

**Comment by atulapra** [comment]
Try to test it for different locations and lighting conditions. Else, use equal number of images of each emotion while training so that it is not skewed towards neutral.
