### ISSUE TITLE
这个需要GPU吗？

### ISSUE THREAD

**Issue by rovesoul** [atulapra/Emotion-detection#19]
is this need GPU? 
I had run it on my computer by CPU. it's running so slowly, so jam.

and I can run kargle's py document,but I can't run TF-single document.because:
"cv2.error: OpenCV(3.4.2) /Users/travis/build/skvark/opencv-python/opencv/modules/objdetect/src/cascadedetect.cpp:1698: error: (-215:Assertion failed) !empty() in function 'detectMultiScale'"

so I tape 'pip install OpenCV-python==3.4.1 ' in terminal  , but it show back this :

ERROR: Could not find a version that satisfies the requirement opencv-python==3.4.1 (from versions: 3.4.2.16, 3.4.2.17, 3.4.3.18, 3.4.4.19, 3.4.5.20, 3.4.6.27, 3.4.7.28, 4.0.0.21, 4.0.1.24, 4.1.0.25, 4.1.1.26)
ERROR: No matching distribution found for opencv-python==3.4.1

emmm...... so hurt

**Comment by atulapra** [comment]
The code runs on both cpu and gpu. As for your second error, try to print or display the image which is passed as input to the detectMultiScale function.
