### ISSUE TITLE
Unable to open webcam

### ISSUE THREAD

**Issue by mahidhar1999** [atulapra/Emotion-detection#21]
Found 28709 images belonging to 7 classes.
Found 7178 images belonging to 7 classes.

when iam running its just classifying dataset but webcam is not opening can you explain why is this happening?

**Comment by atulapra** [comment]
Please check your tensorflow version. And in case you are using tensorflow-gpu, check your cuda and CuDNN versions as well. I am using (on Ubuntu 18.04):
`tensorflow-gpu` = 2.0.0
`cuda` = 10.0
`cudnn` = 7.6.0
