### ISSUE TITLE
Train with new Data set

### ISSUE THREAD

**Issue by jaimerodric** [atulapra/Emotion-detection#24]
Hello! First of all, thanks for your code, it's awesome. I wanna ask you how to train the model with another dataset, to make it better and get a better accuracy. For example, with CK + https://www.kaggle.com/shawon10/ckplus
or with FER2013+ https://github.com/microsoft/FERPlus
In the last case, how do you transform the .csv into png? 
Regards,
Jaime!

**Comment by atulapra** [comment]
That's a good point. I had written a code to convert csv to png for FER2013 as well. I will upload it soon, so that it will be easy to train on new datasets.

**Comment by jaimerodric** [comment]
Thank you so much, I will wait for it and work with your code. Can I use it for a bachelor work? I would reference it. I have tried to get your email to get in touch, but I could not find it. You are doing an amazing code!

**Comment by atulapra** [comment]
Thank you. I have uploaded the code in the src folder.
