### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by sahithya-b** [atulapra/Emotion-detection#25]
during training, it is showing this error:
 File "C:\Users\lenovo\Anaconda3\envs\mypr\lib\site-packages\numpy\core\_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: float() argument must be a string or a number, not 'PngImageFile'

**Comment by atulapra** [comment]
Can you show the full error log?

**Comment by sahithya-b** [comment]
The error is resolved.
thank you.
