### ISSUE TITLE
Percentual values of all emotions

### ISSUE THREAD

**Issue by CutAs** [atulapra/Emotion-detection#27]
Hi, thanks for the code, and your trained model seems to work quite well! 

I'm a bit of a beginner, and I'm working on a project where I'd need to obtain percentile probabilities of all emotions as opposed rounding them up to 1 and then displaying the highest probability. 

What would be the best way to approach this? Thanks!

**Comment by atulapra** [comment]
In line 126 of emotions.py, you can also print the percentage confidence of the max value.

**Comment by CutAs** [comment]
Thanks for a prompt response! What about the other, non-max values?

**Comment by atulapra** [comment]
In line 125, `prediction = model.predict(cropped_img)`, `prediction` is a vector containing probabilities of all emotions. This can be displayed as you require.

**Comment by CutAs** [comment]
Ah, thanks so much, it works! 

I have one last question, if you don't mind. At times the predict() function returns values like "1.1955424988110578e-33", etc. instead of 0 and 1s. Is this related to data loss or am I again getting something wrong?

**Comment by atulapra** [comment]
Since softmax function is being used to get the probabilities, we will not get perfect 0. the number which you have shown is basically an extremely low probability.

**Comment by CutAs** [comment]
Makes sense, thanks!
