### ISSUE TITLE
KeyError 'acc'

### ISSUE THREAD

**Issue by JRitmeester** [atulapra/Emotion-detection#29]
I'm not sure how you even ran the code with this error. 
`  File "emotions.py", line 98, in <module>
    plot_model_history(model_info)
  File "emotions.py", line 26, in plot_model_history
    axs[0].plot(range(1,len(model_history.history['acc'])+1),model_history.history['acc'])
KeyError: 'acc'`

You should replace all instances of `'accuracy'` with `'acc'`, or vice versa.

**Comment by atulapra** [comment]
In older versions of Keras, the dictionary key was called 'acc', which has been changed to 'accuracy'. Thank you for pointing this out. It has been replaced.
