### ISSUE TITLE
The system cannot find the path specified: 'data/train'

### ISSUE THREAD

**Issue by AnkitBasrur** [atulapra/Emotion-detection#30]
On running this line python emotions.py --mode train, I'm getting this error: The system cannot find the path specified: 'data/train'. Please help as I'm new to data science.

**Comment by atulapra** [comment]
Have you downloaded and extracted the dataset?

**Comment by AnkitBasrur** [comment]
Oh, actually I kept it in wrong directory. Anyways great project
