### ISSUE TITLE
TypeError: 'float' object is not iterable

### ISSUE THREAD

**Issue by wenhuiwang93** [atulapra/Emotion-detection#46]
Hi
When I execute the code 'python emotions.py --mode train', 
after 50/50 epoches, it occurs this error, can't generate new training files. How can I solve this error???

full error:
Traceback (most recent call last):
  File "emotions.py", line 98, in <module>
    plot_model_history(model_info)
  File "emotions.py", line 31, in plot_model_history
    axs[0].set_xticks(np.arange(1,len(model_history.history['accuracy'])+1),len(model_history.history['accuracy'])/10)
  File "/home/jaeger/.local/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 75, in wrapper
    return get_method(self)(*args, **kwargs)
  File "/home/jaeger/.local/lib/python3.8/site-packages/matplotlib/axis.py", line 1857, in set_ticks
    self.set_ticklabels(labels, minor=minor, **kwargs)
  File "/home/jaeger/.local/lib/python3.8/site-packages/matplotlib/axis.py", line 1712, in set_ticklabels
    ticklabels = [t.get_text() if hasattr(t, 'get_text') else t
TypeError: 'float' object is not iterable

thanks.

**Comment by wenhuiwang93** [comment]
solved。
axis.py:

-ticklabels = [t.get_text() if hasattr(t, 'get_text') else t
-                for t in ticklabels]
+ticklabels = []
+    for t in ticklabels:
+        if hasattr(t, 'get_text'):
+              ticklabels.append(t.get_text())

**Comment by melikeey** [comment]
I did not understand solution...

what do you mean -ticklabels + ticklabels

**Comment by wenhuiwang93** [comment]
> I did not understand solution...
> 
> what do you mean -ticklabels + ticklabels

Sorry for the confusion, I re-edited the answer，is that clear？

**Comment by melikeey** [comment]
yes It works, Thank you :) Apart from that, I am trying to increase the accuracy model, is there a method you would recommend? @wenhuiwang93

**Comment by melikeey** [comment]
For increasing: 
I am changing CNN layers, changing num_val and num_train values. I haven't reached a higher value yet.

**Comment by wenhuiwang93** [comment]
> For increasing: I am changing CNN layers, changing num_val and num_train values. I haven't reached a higher value yet.

lower the learning-rate？maybe transfer learning and fine tune can help you。Go to the following website, it should help you。  
https://tensorflow.google.cn/tutorials?hl=zh_cn
