### ISSUE TITLE
The model is not loaded.

### ISSUE THREAD

**Issue by snowalala** [atulapra/Emotion-detection#6]
Hi, thanks for your sharing. When I used **python em_model.py singleface** , the screen is always one emotion, the result is all like this:
...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]

I think that the project isn't loaded model. But I have placed the **DATA** in the **Emotion-detection-master**, and run it as you. Please help me about this question. I don't know why the model isn't run. Thank you very much!

**Comment by atulapra** [comment]
The folder structure is of the form: 
Emotion-detection:
- emojis (folder)
- examples (folder)
-  haarcascade_files (folder)
- em_model.py (file)
- multiface.py (file)
- singleface.py (file)
- README.md (file)
- model_1_atul.tflearn.data-00000-of-00001 (file)
- model_1_atul.tflearn.index (file)
- model_1_atul.tflearn.meta (file)

**Comment by snowalala** [comment]
I really appreciate your timely help!

**Comment by siksik92** [comment]
hello , thanks for your sharing .I'm korean student studying about computer vision and opencv and prefaring project about this and this project really helped our project and very useful.
I have question about this project . first when I run the singleface It detects emotion very well
but it isn't in multiface . I don't know what is the reason.... 
from muliface.py line 40 
            if result is not None:
                result[0][2] -= 0.15
                result[0][4] -= 0.15
                if result[0][3] > 0.06:
               result[0][3] += 0.4
can you explain why these codes are used only in muliface.py  not in singleface.py
(singleface.py doesn't use these codes for detecting emotion)
please help me... thank you!!

**Comment by atulapra** [comment]
That part of the code was used by me to ensure good results in different lighting conditions. It is unneccesary otherwise and has been removed.

**Comment by xiang1107** [comment]
hello, how can i get these files?
=======================
--model_1_atul.tflearn.data-00000-of-00001 (file)
--model_1_atul.tflearn.index (file)
--model_1_atul.tflearn.meta (file)
=======================
thank you ！

**Comment by atulapra** [comment]
Please check the earlier commits in the README. Link is provided there.

**Comment by xiang1107** [comment]
Thank you very much!
